-- V2: Relational evolution — city, soft delete, categories, and foreign keys

ALTER TABLE venues ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT '';

ALTER TABLE events ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE events ADD COLUMN venue_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE events ADD CONSTRAINT fk_event_venue FOREIGN KEY (venue_id) REFERENCES venues(id);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE events_categories (
    event_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (event_id, category_id),
    CONSTRAINT fk_ec_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_ec_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
